{{- if and .Values.agent.enabled .Values.agent.hub.token (not .Values.agent.hub.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netcat.agentName" . }}-hub
  namespace: {{ include "netcat.namespace" . }}
  labels:
    {{- include "netcat.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.agent.hub.token | quote }}
{{- end }}
