{{- if .Values.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "netcat.agentName" . }}
  namespace: {{ include "netcat.namespace" . }}
  labels:
    {{- include "netcat.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
{{- end }}
