{{- if and .Values.controller.enabled .Values.controller.kubeconfig.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "netcat.controllerName" . }}
  labels:
    {{- include "netcat.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/proxy"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "netcat.controllerName" . }}
  labels:
    {{- include "netcat.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "netcat.controllerName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "netcat.controllerName" . }}
    namespace: {{ include "netcat.namespace" . }}
{{- end }}
